import Link from "next/link";

export const metadata = {
  title: "Privacy — Byparsathy",
  description: "How Byparsathy collects, uses, and protects your data.",
};

const SECTIONS = [
  {
    h: "What we collect",
    p: "Account details you provide (name, username, email, password), profile content (company or creator information, portfolio items, social links), and activity generated by using the platform (campaigns, applications, messages, reviews).",
  },
  {
    h: "How we use it",
    p: "To operate your account, match businesses with creators, deliver notifications, and keep the platform safe. We never sell your personal data.",
  },
  {
    h: "What is visible",
    p: "Promoter profiles, portfolio items, campaign listings marked public, and reviews are visible to other users as part of the marketplace. Account credentials and private messages are never shared.",
  },
  {
    h: "Your control",
    p: "You can edit your profile at any time. To delete your account and personal data, contact your workspace administrator.",
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-linen-canvas">
      <div className="mx-auto max-w-[800px] px-6 pb-24 pt-28">
        <Link href="/" className="text-sm font-medium text-signal-blue hover:opacity-80">
          ← Back home
        </Link>
        <h1 className="mb-2 mt-6 text-heading-lg text-midnight-ink">Privacy Policy</h1>
        <p className="mb-10 text-sm text-ash">Last updated: 2026</p>
        <div className="flex flex-col gap-8">
          {SECTIONS.map((s) => (
            <section key={s.h}>
              <h2 className="mb-2 text-heading-sm text-graphite">{s.h}</h2>
              <p className="text-body leading-relaxed text-steel">{s.p}</p>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
