"""Add deliverables table

Revision ID: b2dd85e0af69
Revises: 6ddb6811b64c
Create Date: 2026-06-29 08:37:03.570380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2dd85e0af69'
down_revision: Union[str, None] = '6ddb6811b64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('content_url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'REVISION_REQUESTED', 'PUBLISHED', name='deliverablestatus'), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_collaboration_id'), 'deliverables', ['collaboration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliverables_collaboration_id'), table_name='deliverables')
    op.drop_table('deliverables')
    # ### end Alembic commands ###

